Traceback (most recent call last):
  File "streaming.py", line 123, in <module>
    run(api)
  File "streaming.py", line 113, in run
    api.filter(track=[useraccount])
  File "/Library/Python/2.7/site-packages/tweepy-2.0-py2.7.egg/tweepy/streaming.py", line 230, in filter
    
  File "/Library/Python/2.7/site-packages/tweepy-2.0-py2.7.egg/tweepy/streaming.py", line 171, in _start
    
  File "/Library/Python/2.7/site-packages/tweepy-2.0-py2.7.egg/tweepy/streaming.py", line 117, in _run
    if __name__ == "__main__":
  File "/Library/Python/2.7/site-packages/tweepy-2.0-py2.7.egg/tweepy/streaming.py", line 149, in _read_loop
    
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 541, in read
    return self._read_chunked(amt)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 574, in _read_chunked
    line = self.fp.readline(_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 232, in recv
    return self.read(buflen)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 151, in read
    return self._sslobj.read(len)
ssl.SSLError: The read operation timed out
